### ISSUE TITLE
unzip signature

### ISSUE THREAD

**Issue by volkovskiyda** [maxoly/fastlane-plugin-unzip#1]
Hi. I'm using fastlane on Windows (I know about "support" fastlane on Windows :) ), and I can't solve unzip problem. I find your plugin, but it's signature does not suitable for my needs. Is it possible to change signature of call? Instead of using unzip(file: "archive.zip", destination_path: "./path/to/other/folder/")
just "unzip archive.zip -d /path/to/other/folder/". Thanks.

**Comment by janpio** [comment]
Where do you want to use that new "command" `unzip archive.zip -d /path/to/other/folder/` @volkovskiyda? In your `Fastfile`? This plugin action works just fine on Windows as it is.

**Comment by volkovskiyda** [comment]
Fastlane run this method with the signature 'unzip archive.zip -d /path/to/other/folder/`, and Windows can't handle the action. Do you have any examples of fastfile for Windows? Thanks
